# 5-node, sync any/2, required durability, NO failover quorum.
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pglab
spec:
  instances: 5
  postgresql:
    synchronous:
      method: any
      number: 2
      dataDurability: required
  storage:
    size: 1Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
